-- INSERT  INTO users(username,password) VALUES ('admin','aaa');
-- INSERT  INTO users(username,password) VALUES ('admin','bb');
-- INSERT  INTO users(username,password) VALUES ('admin','cc');
-- INSERT  INTO users(username,password) VALUES ('admin','dd');